import { useCallback, useEffect, useMemo, useState } from "react";
import { apiRequest } from "../../../lib/api";
import { confirmDelete, showError, showSuccess } from "../../../lib/alerts";

const TABS = [["summary","Summary"],["types","Service Types"],["categories","Categories"],["services","Services"],["prices","Price Versions"],["rules","Pricing Rules"],["branch-pricing","Branch Pricing"],["history","History & Export"]];
const inputClass="h-[40px] w-full rounded border border-[#ccd9de] bg-white px-3 text-[13px] outline-none focus:border-[#2b8791] focus:ring-2 focus:ring-[#2b8791]/10";
const today=()=>new Date().toISOString().slice(0,10);
const emptyFor=(entity)=>({
  types:{code:"",name:"",description:"",is_active:true,sort_order:0},
  categories:{service_type_id:"",code:"",name:"",description:"",is_active:true,sort_order:0},
  services:{service_type_id:"",service_category_id:"",code:"",name:"",description:"",billing_unit:"unit",hospital_id:"",branch_id:"",requires_approval:false,is_taxable:false,status:"active"},
  prices:{service_id:"",hospital_id:"",branch_id:"",payer_type:"self",payer_reference:"",currency_code:"BDT",amount:"",tax_rate:0,effective_from:today(),effective_to:""},
  rules:{service_id:"",service_category_id:"",hospital_id:"",branch_id:"",code:"",name:"",rule_type:"percentage_discount",value:"",payer_type:"all",payer_reference:"",priority:100,effective_from:today(),effective_to:""},
}[entity]);
const label=(value)=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,char=>char.toUpperCase());
const money=(value,currency="BDT")=>`${currency} ${Number(value||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const fetchAllPages=async(path)=>{const first=await apiRequest(path);const items=[...(first.data||[])];const pagination=first.meta?.pagination;if(!pagination?.has_next)return {...first,data:items};for(let page=pagination.page+1;page<=pagination.total_pages;page+=1){const joiner=path.includes("?")?"&":"?";const response=await apiRequest(`${path}${joiner}page=${page}`);items.push(...(response.data||[]));}return {...first,data:items};};
const Field=({label:caption,children})=><label className="block"><span className="mb-1 block text-[11px] font-semibold uppercase tracking-wide text-[#5c6b73]">{caption}</span>{children}</label>;
const statusClass=(status)=>({approved:"bg-green-100 text-green-800",pending:"bg-amber-100 text-amber-800",rejected:"bg-red-100 text-red-800",active:"bg-cyan-100 text-cyan-800",draft:"bg-slate-100 text-slate-700",retired:"bg-gray-200 text-gray-700"}[status]||"bg-slate-100 text-slate-700");

function Select({children,...props}){return <select className={inputClass} {...props}>{children}</select>}
function SummaryCard({caption,value,detail}){return <div className="rounded-[8px] border border-[#cfe2e5] bg-white p-4 shadow-sm"><p className="text-[11px] font-semibold uppercase tracking-wide text-[#708087]">{caption}</p><p className="mt-2 text-[26px] font-bold text-[#236f78]">{value}</p>{detail?<p className="mt-1 text-[11px] text-[#7b888f]">{detail}</p>:null}</div>}

function Summary({meta,summaryRows}){
  const [serviceId,setServiceId]=useState("");const [result,setResult]=useState(null);const [busy,setBusy]=useState(false);
  const resolve=async()=>{if(!serviceId)return;setBusy(true);try{const response=await apiRequest(`/service-catalog/resolve?service_id=${serviceId}&payer_type=self`);setResult(response.data);}catch(error){showError("Price not found",error.message);}finally{setBusy(false)}};
  const summary=meta.summary||{};
  return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6"><SummaryCard caption="Types" value={summary.types||0}/><SummaryCard caption="Categories" value={summary.categories||0}/><SummaryCard caption="Services" value={summary.services||0}/><SummaryCard caption="Price Versions" value={summary.prices||0}/><SummaryCard caption="Rules" value={summary.rules||0}/><SummaryCard caption="Approved Value" value={money(summary.approved_price_value)} detail="Sum of approved catalogue rows"/></div><div className="overflow-hidden rounded-[8px] border border-[#d8e3e6] bg-white"><div className="border-b border-[#e1e9eb] p-4"><h2 className="text-[17px] font-semibold text-[#203139]">Service-wise charge summary</h2><p className="text-[11px] text-[#718087]">Live approved-price coverage by service type.</p></div><div className="overflow-x-auto"><table className="min-w-[760px] w-full text-left text-[12px]"><thead className="bg-[#eaf4f5]"><tr><th className="p-3">Service type</th><th className="p-3">Services</th><th className="p-3">Approved prices</th><th className="p-3">Minimum</th><th className="p-3">Maximum</th><th className="p-3">Average</th></tr></thead><tbody>{(summaryRows||[]).map(row=><tr className="border-t border-[#e6edef]" key={row.service_type_id}><td className="p-3"><b>{row.name}</b><small className="block text-[#78868d]">{row.code}</small></td><td className="p-3">{row.service_count}</td><td className="p-3">{row.approved_price_count}</td><td className="p-3">{money(row.min_price)}</td><td className="p-3">{money(row.max_price)}</td><td className="p-3">{money(row.average_price)}</td></tr>)}</tbody></table></div></div><div className="rounded-[8px] border border-[#d8e3e6] bg-white p-5"><h2 className="text-[17px] font-semibold text-[#203139]">Live price resolver</h2><p className="mt-1 text-[12px] text-[#718087]">This is the same approved, effective and scope-aware price lookup used when a clinical invoice is created.</p><div className="mt-4 flex max-w-[700px] gap-3 max-sm:flex-col"><Select onChange={event=>setServiceId(event.target.value)} value={serviceId}><option value="">Select a service</option>{(meta.services||[]).map(item=><option key={item.id} value={item.id}>{item.code} — {item.name}</option>)}</Select><button className="rounded bg-[#263940] px-6 text-[12px] font-semibold text-white disabled:opacity-50" disabled={!serviceId||busy} onClick={resolve} type="button">{busy?"RESOLVING…":"RESOLVE"}</button></div>{result?<div className="mt-4 grid gap-3 rounded bg-[#effafa] p-4 text-[12px] md:grid-cols-4"><div><b>Final price</b><p className="text-[20px] text-[#19666e]">{money(result.amount,result.currency_code)}</p></div><div><b>Base</b><p>{money(result.base_amount,result.currency_code)}</p></div><div><b>Tax</b><p>{result.tax_rate}%</p></div><div><b>Version / scope</b><p>v{result.version_no} · {result.scope.branch_id?"Branch":result.scope.hospital_id?"Hospital":"Organization"}</p></div></div>:null}</div></div>;
}

function Editor({entity,meta,selected,onSaved,onCancel}){
  const [form,setForm]=useState(()=>selected?{...emptyFor(entity),...selected}:emptyFor(entity));const [saving,setSaving]=useState(false);
  useEffect(()=>setForm(selected?{...emptyFor(entity),...selected}:emptyFor(entity)),[entity,selected]);
  const set=(key,value)=>setForm(current=>({...current,[key]:value}));
  const selectOptions=(items,valueKey="id")=>(items||[]).map(item=><option key={item[valueKey]} value={item[valueKey]}>{item.code?`${item.code} — `:""}{item.name}</option>);
  const submit=async event=>{event.preventDefault();setSaving(true);try{const payload={...form};["service_type_id","service_category_id","service_id","hospital_id","branch_id","sort_order","priority"].forEach(key=>{if(payload[key]!==undefined)payload[key]=payload[key]===""?null:Number(payload[key]);});["amount","tax_rate","value"].forEach(key=>{if(payload[key]!==undefined)payload[key]=Number(payload[key]||0);});["effective_to","payer_reference","description"].forEach(key=>{if(payload[key]==="")payload[key]=null;});delete payload.id;delete payload.created_at;delete payload.updated_at;delete payload.deleted_at;delete payload.type;delete payload.category;delete payload.prices;delete payload.approval_request_id;delete payload.approved_by;delete payload.approved_at;delete payload.version_no;delete payload.rejection_reason;await apiRequest(`/service-catalog/${entity}${selected?`/${selected.id}`:""}`,{method:selected?"PATCH":"POST",body:JSON.stringify(payload)});showSuccess(selected?"Updated":"Created",`${label(entity.slice(0,-1))} saved successfully.`);onSaved();}catch(error){showError("Could not save",error.message);}finally{setSaving(false)}};
  return <form className="rounded-[8px] border border-[#d8e3e6] bg-white p-5" onSubmit={submit}><div className="mb-4 flex items-center justify-between"><div><h2 className="text-[17px] font-semibold text-[#203139]">{selected?"Edit":"New"} {label(entity.slice(0,-1))}</h2><p className="text-[11px] text-[#718087]">Changes are written to the database and recorded by the audit trail.</p></div>{selected?<button className="text-[12px] text-[#6b7a82]" onClick={onCancel} type="button">Cancel edit</button>:null}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
    {entity!=="prices"?<Field label="Name"><input className={inputClass} onChange={e=>set("name",e.target.value)} required value={form.name||""}/></Field>:null}
    {entity!=="prices"?<Field label="Code"><input className={inputClass} onChange={e=>set("code",e.target.value)} placeholder="Auto-generated if blank" value={form.code||""}/></Field>:null}
    {entity==="categories"||entity==="services"?<Field label="Service type"><Select onChange={e=>{set("service_type_id",e.target.value);if(entity==="services")set("service_category_id","")}} required value={form.service_type_id||""}><option value="">Select type</option>{selectOptions(meta.types)}</Select></Field>:null}
    {entity==="services"||entity==="rules"?<Field label="Category"><Select onChange={e=>set("service_category_id",e.target.value)} value={form.service_category_id||""}><option value="">{entity==="rules"?"Any / select if service blank":"Select category"}</option>{selectOptions((meta.categories||[]).filter(item=>!form.service_type_id||Number(item.service_type_id)===Number(form.service_type_id)))}</Select></Field>:null}
    {entity==="prices"||entity==="rules"?<Field label="Service"><Select onChange={e=>set("service_id",e.target.value)} required={entity==="prices"} value={form.service_id||""}><option value="">{entity==="rules"?"Category-wide rule":"Select service"}</option>{selectOptions(meta.services)}</Select></Field>:null}
    {entity==="services"?<Field label="Billing unit"><input className={inputClass} onChange={e=>set("billing_unit",e.target.value)} required value={form.billing_unit||"unit"}/></Field>:null}
    {entity==="prices"?<><Field label="Amount"><input className={inputClass} min="0" onChange={e=>set("amount",e.target.value)} required step="0.01" type="number" value={form.amount}/></Field><Field label="Currency"><input className={inputClass} maxLength="3" onChange={e=>set("currency_code",e.target.value.toUpperCase())} required value={form.currency_code}/></Field><Field label="Tax rate %"><input className={inputClass} min="0" onChange={e=>set("tax_rate",e.target.value)} step="0.0001" type="number" value={form.tax_rate}/></Field></>:null}
    {entity==="rules"?<><Field label="Rule type"><Select onChange={e=>set("rule_type",e.target.value)} value={form.rule_type}>{["percentage_discount","flat_discount","surcharge","tax_override"].map(item=><option key={item} value={item}>{label(item)}</option>)}</Select></Field><Field label="Value"><input className={inputClass} min="0" onChange={e=>set("value",e.target.value)} required step="0.0001" type="number" value={form.value}/></Field><Field label="Priority"><input className={inputClass} onChange={e=>set("priority",e.target.value)} type="number" value={form.priority}/></Field></>:null}
    {entity==="prices"||entity==="rules"?<><Field label="Payer type"><Select onChange={e=>set("payer_type",e.target.value)} value={form.payer_type}>{["self","all","corporate","insurance","government"].map(item=><option key={item} value={item}>{label(item)}</option>)}</Select></Field><Field label="Payer reference"><input className={inputClass} onChange={e=>set("payer_reference",e.target.value)} placeholder="Optional company/insurer code" value={form.payer_reference||""}/></Field><Field label="Effective from"><input className={inputClass} onChange={e=>set("effective_from",e.target.value)} required type="date" value={String(form.effective_from||"").slice(0,10)}/></Field><Field label="Effective to"><input className={inputClass} onChange={e=>set("effective_to",e.target.value)} type="date" value={String(form.effective_to||"").slice(0,10)}/></Field></>:null}
    {entity==="services"||entity==="prices"||entity==="rules"?<><Field label="Hospital scope"><Select onChange={e=>{set("hospital_id",e.target.value);set("branch_id","")}} value={form.hospital_id||""}><option value="">Organization-wide</option>{selectOptions(meta.hospitals)}</Select></Field><Field label="Branch scope"><Select disabled={!form.hospital_id} onChange={e=>set("branch_id",e.target.value)} value={form.branch_id||""}><option value="">All hospital branches</option>{selectOptions((meta.branches||[]).filter(item=>Number(item.hospital_id)===Number(form.hospital_id)))}</Select></Field></>:null}
    {entity==="types"||entity==="categories"?<Field label="Sort order"><input className={inputClass} min="0" onChange={e=>set("sort_order",e.target.value)} type="number" value={form.sort_order}/></Field>:null}
    {entity==="types"||entity==="categories"||entity==="services"?<Field label="Description"><input className={inputClass} onChange={e=>set("description",e.target.value)} value={form.description||""}/></Field>:null}
  </div><div className="mt-4 flex justify-end"><button className="rounded bg-[#237780] px-6 py-2.5 text-[12px] font-semibold text-white disabled:opacity-50" disabled={saving} type="submit">{saving?"SAVING…":selected?"UPDATE":"SAVE"}</button></div></form>;
}

function RecordTable({entity,rows,loading,onEdit,onChanged,readOnly=false}){
  const remove=async row=>{if(!await confirmDelete("Delete catalogue record?",`Delete ${row.name||row.service?.name||`record #${row.id}`}?`))return;try{await apiRequest(`/service-catalog/${entity}/${row.id}`,{method:"DELETE"});showSuccess("Deleted","Catalogue record removed.");onChanged();}catch(error){showError("Delete failed",error.message)}};
  const decision=async(row,action)=>{try{const body=action==="reject"?{comments:window.prompt("Rejection reason")||""}:{};if(action==="reject"&&!body.comments)return;await apiRequest(`/service-catalog/${entity}/${row.id}/${action}`,{method:"POST",body:JSON.stringify(body)});showSuccess(label(action),`Record ${action}d successfully.`);onChanged();}catch(error){showError(`${label(action)} failed`,error.message)}};
  const columns=entity==="types"?["Code","Name","Active"]:entity==="categories"?["Code","Name","Type"]:entity==="services"?["Code","Service","Type / Category","Unit","Status"]:entity==="prices"?["Service","Amount","Payer","Scope","Effective","Version","Status"]:["Code","Rule","Target","Value","Effective","Status"];
  const cells=row=>entity==="types"?[row.code,row.name,row.is_active?"Yes":"No"]:entity==="categories"?[row.code,row.name,row.type?.name||"—"]:entity==="services"?[row.code,row.name,`${row.type?.name||"—"} / ${row.category?.name||"—"}`,row.billing_unit,<span className={`rounded-full px-2 py-1 ${statusClass(row.status)}`}>{label(row.status)}</span>]:entity==="prices"?[row.service?.name||`#${row.service_id}`,money(row.amount,row.currency_code),label(row.payer_type),row.branch?.name||row.hospital?.name||(row.branch_id?`Branch #${row.branch_id}`:row.hospital_id?`Hospital #${row.hospital_id}`:"Organization"),`${row.effective_from} → ${row.effective_to||"Open"}`,`v${row.version_no}`,<span className={`rounded-full px-2 py-1 ${statusClass(row.status)}`}>{label(row.status)}</span>]:[row.code,row.name,row.service?.name||row.category?.name||"—",`${label(row.rule_type)} · ${row.value}`,`${row.effective_from} → ${row.effective_to||"Open"}`,<span className={`rounded-full px-2 py-1 ${statusClass(row.status)}`}>{label(row.status)}</span>];
  return <div className="overflow-hidden rounded-[8px] border border-[#d8e3e6] bg-white"><div className="overflow-x-auto"><table className="min-w-[950px] w-full text-left text-[12px]"><thead className="bg-[#eaf4f5]"><tr>{columns.map(item=><th className="p-3" key={item}>{item}</th>)}{!readOnly?<th className="p-3 text-right">Actions</th>:null}</tr></thead><tbody>{loading?<tr><td className="p-10 text-center" colSpan={columns.length+(readOnly?0:1)}>Loading live catalogue…</td></tr>:null}{!loading&&!rows.length?<tr><td className="p-10 text-center text-[#718087]" colSpan={columns.length+(readOnly?0:1)}>No database records found.</td></tr>:null}{!loading?rows.map(row=><tr className="border-t border-[#e6edef]" key={row.id}>{cells(row).map((cell,index)=><td className="p-3" key={index}>{cell}</td>)}{!readOnly?<td className="p-3"><div className="flex justify-end gap-1">{["prices","rules"].includes(entity)&&row.status==="draft"?<button className="rounded border border-amber-200 px-2 py-1 text-amber-700" onClick={()=>decision(row,"submit")} type="button">Submit</button>:null}{["prices","rules"].includes(entity)&&["draft","pending"].includes(row.status)?<><button className="rounded border border-green-200 px-2 py-1 text-green-700" onClick={()=>decision(row,"approve")} type="button">Approve</button><button className="rounded border border-red-200 px-2 py-1 text-red-600" onClick={()=>decision(row,"reject")} type="button">Reject</button></>:null}{!["approved","retired"].includes(row.status)?<button className="rounded border border-blue-200 px-2 py-1 text-blue-700" onClick={()=>onEdit(row)} type="button">Edit</button>:null}{!["approved","retired"].includes(row.status)?<button className="rounded border border-red-200 px-2 py-1 text-red-600" onClick={()=>remove(row)} type="button">Delete</button>:<span className="rounded bg-slate-100 px-2 py-1 text-slate-600">Immutable</span>}</div></td>:null}</tr>):null}</tbody></table></div></div>;
}

export function ServiceCataloguePage(){
  const [tab,setTab]=useState("summary");const [meta,setMeta]=useState({});const [rows,setRows]=useState([]);const [summaryRows,setSummaryRows]=useState([]);const [loading,setLoading]=useState(true);const [selected,setSelected]=useState(null);const [search,setSearch]=useState("");
  const readOnly=["history","branch-pricing"].includes(tab);
  const entity=readOnly?"prices":tab;
  const load=useCallback(async()=>{setLoading(true);try{const listPath=tab==="history"?`/service-catalog/reports/price-history?limit=100${search?`&search=${encodeURIComponent(search)}`:""}`:tab==="branch-pricing"?`/service-catalog/reports/branch-pricing?limit=100${search?`&search=${encodeURIComponent(search)}`:""}`:`/service-catalog/${entity}?limit=100${search?`&search=${encodeURIComponent(search)}`:""}`;const [metaResponse,listResponse,summaryResponse]=await Promise.all([apiRequest("/service-catalog/meta"),entity==="summary"?Promise.resolve({data:[]}):fetchAllPages(listPath),apiRequest("/service-catalog/reports/service-summary")]);const metaData=metaResponse.data||{};if(entity!=="summary"&&entity!=="services"){const services=await fetchAllPages("/service-catalog/services?limit=100");metaData.services=services.data||[];}else if(entity==="services")metaData.services=listResponse.data||[];else{const services=await fetchAllPages("/service-catalog/services?limit=100");metaData.services=services.data||[];}setMeta(metaData);setRows(listResponse.data||[]);setSummaryRows(summaryResponse.data||[]);}catch(error){showError("Catalogue could not load",error.message);setRows([]);}finally{setLoading(false)}},[entity,search,tab]);
  useEffect(()=>{setSelected(null);load()},[load]);
  const exportCsv=()=>{const source=rows.map(row=>({id:row.id,code:row.code||"",name:row.name||row.service?.name||"",amount:row.amount||"",currency:row.currency_code||"",payer:row.payer_type||"",effective_from:row.effective_from||"",effective_to:row.effective_to||"",version:row.version_no||"",status:row.status||""}));const headers=Object.keys(source[0]||{id:"",code:"",name:"",amount:"",currency:"",payer:"",effective_from:"",effective_to:"",version:"",status:""});const csv=[headers,...source.map(item=>headers.map(key=>item[key]))].map(line=>line.map(cell=>`"${String(cell??"").replaceAll('"','""')}"`).join(",")).join("\n");const link=document.createElement("a");link.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));link.download=`service-catalog-${entity}-${today()}.csv`;link.click();URL.revokeObjectURL(link.href)};
  const pageRows=useMemo(()=>tab==="history"?[...rows].sort((a,b)=>Number(b.version_no)-Number(a.version_no)||Number(b.id)-Number(a.id)):rows,[rows,tab]);
  return <section className="mx-auto max-w-[1450px] space-y-4"><div className="rounded-[8px] bg-[#276f78] px-5 py-4 text-white"><h1 className="text-[21px] font-semibold">Enterprise Service & Charge Catalogue</h1><p className="mt-1 text-[12px] text-white/80">One governed source for consultation, laboratory, radiology, bed, ambulance, pharmacy and blood-bank prices.</p></div><div className="flex gap-1 overflow-x-auto rounded-[8px] border border-[#d8e3e6] bg-white p-2">{TABS.map(([key,title])=><button className={`whitespace-nowrap rounded px-4 py-2 text-[12px] font-semibold ${tab===key?"bg-[#237780] text-white":"text-[#53636b] hover:bg-[#edf5f6]"}`} key={key} onClick={()=>setTab(key)} type="button">{title}</button>)}</div>{tab==="summary"?<Summary meta={meta} summaryRows={summaryRows}/>:<><div className="flex flex-wrap items-center justify-between gap-3 rounded-[8px] border border-[#d8e3e6] bg-white p-3"><div><h2 className="text-[16px] font-semibold text-[#203139]">{TABS.find(item=>item[0]===tab)?.[1]}</h2><p className="text-[11px] text-[#718087]">{tab==="history"?"Immutable price versions and approval outcomes from the database.":tab==="branch-pricing"?"Approved branch-specific prices from the database.":"Create, review and govern live catalogue records."}</p></div><div className="flex gap-2"><input className={`${inputClass} w-[230px]`} onChange={event=>setSearch(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")load()}} placeholder="Search records" value={search}/><button className="rounded border border-blue-200 px-4 text-[11px] font-semibold text-blue-700" onClick={load} type="button">REFRESH</button><button className="rounded border border-green-200 px-4 text-[11px] font-semibold text-green-700" disabled={!pageRows.length} onClick={exportCsv} type="button">EXPORT CSV</button></div></div>{!readOnly?<Editor entity={entity} meta={meta} onCancel={()=>setSelected(null)} onSaved={()=>{setSelected(null);load()}} selected={selected}/>:null}<RecordTable entity={entity} loading={loading} onChanged={load} onEdit={readOnly?()=>{}:setSelected} readOnly={readOnly} rows={pageRows}/></>}</section>;
}
